type: PROVISION_K8S_DEPLOYMENT
spec:
  replicas: '2'
  selector:
    matchLabels:
      app: 'nginx_calm_@@{project_name}@@@@{build_number}@@'
  template:
    metadata:
      labels:
        app: 'nginx_calm_@@{project_name}@@@@{build_number}@@'
      namespace: default
      name: NginxPod
    type: PROVISION_K8S_POD
    spec:
      containers:
      - name: nginx-container
        ports:
        - protocol: TCP
          containerPort: 8080
        env:
        - name: NODEJS_IP_ADDRESS
          value: '@@{nodejs_deploymentPublished_Service.ingress}@@'
        image: '@@{docker_registry}@@/@@{project_name}@@/nginx:0.1.@@{build_number}@@'
        imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
      - name: 'docker-registry-cred-@@{cicd_app_name}@@'
metadata:
  namespace: default
  name: 'k8s-nginx-deployment-@@{calm_random}@@'
