version: '2'

services:
  mongodb:
    image: mongo:jammy
    ports:
      - "27017:27017"

  mongo-seed:
    build: 
      context: ../../
      dockerfile: db/mongo/docker/dev/Dockerfile
    links:
      - mongodb

  nodejs:
    build: 
      context: ../../
      dockerfile: app/docker/dev/Dockerfile
    links:
      - mongodb
      - mongo-seed
    environment:
      MONGODB_HOST: mongodb
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: ../../
      dockerfile: web/docker/dev/Dockerfile
    links:
      - nodejs
    environment:
      NODEJS_IP_ADDRESS: $NODEJS_IP_ADDRESS
    ports:
      - "80:80"
